{% set name = "arviz" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9df7592f1ce77ce69f7504dba13f8d550204c49c23e54849861dbcb2c640954

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=60.0.0
    - wheel
  run:
    - python
    - matplotlib-base >=3.8
    - numpy >=1.26.0
    - scipy >=1.11.0
    - pandas >=2.1.0
    - xarray >=2023.7.0
    - h5netcdf >=1.0.2
    - packaging
    - typing_extensions >=4.1.0
    - setuptools >=60.0.0
    - typing-extensions >=4.1.0
    - xarray-einstats >=0.3
  run_constrained:
    - bokeh >=3
    - zarr >=2.5.0,<3
    - dm-tree >=0.1.8
    - xarray >=2024.11.0

test:
  source_files:
    - arviz
  imports:
    - arviz
  requires:
    - pip
    - pytest
    - pytest-cov
    - cloudpickle
    - bokeh >=1.4.0
  commands:
    - pip check
    - pytest arviz/tests --ignore="arviz/tests/external_tests" -k "not (test_io_function or test_io_method or test_warning_rc_file or test_bad_rc_file or test_deterministic or test_empty_inference_data_object or test_rctemplate_updated or test_rc_context_file or test_plot_trace_legend or test_plot_ppc_transposed)"  # [not win]
    - pytest arviz/tests --ignore="arviz/tests/external_tests" --ignore="arviz/tests/base_tests/test_plots_bokeh.py" --ignore="arviz/tests/base_tests/test_plots_matplotlib.py" -k "not (test_io_function or test_io_method or test_warning_rc_file or test_bad_rc_file or test_deterministic or test_empty_inference_data_object or test_rctemplate_updated or test_rc_context_file or test_plot_forest_single_value or test_plot_density_discrete_combinedims or test_plot_violin or test_plot_density_float)"  # [win]

about:
  home: https://github.com/arviz-devs/arviz
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Exploratory analysis of Bayesian models with Python
  description: |
    ArviZ (pronounced "AR-vees") is a Python package for exploratory analysis
    of Bayesian models. Includes functions for posterior analysis, model
    checking, comparison and diagnostics.

  doc_url: https://arviz-devs.github.io/arviz/index.html
  dev_url: https://github.com/arviz-devs/arviz

extra:
  recipe-maintainers:
    - ericmjl
    - canyon289
    - aloctavodia
    - ColCarroll
    - ahartikainen
