{% set name = "arviz" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b46dc693e34fd3dff20d824234c7a01cb04b1b536441e285218c54fab42c3c09

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=60.0.0
    - wheel
  run:
    - python
    - matplotlib-base >=3.5
    - numpy >=1.22.0,<2.0
    - scipy >=1.8.0
    - pandas >=1.4.0
    - xarray >=0.21.0
    - h5netcdf >=1.0.2
    - packaging
    - typing_extensions >=4.1.0
    - xarray-einstats >=0.3

test:
  imports:
    - arviz
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/arviz-devs/arviz
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Exploratory analysis of Bayesian models with Python

  description: |
    ArviZ (pronounced "AR-vees") is a Python package for exploratory analysis
    of Bayesian models. Includes functions for posterior analysis, model
    checking, comparison and diagnostics.

  doc_url: https://arviz-devs.github.io/arviz/index.html
  dev_url: https://github.com/arviz-devs/arviz

extra:
  recipe-maintainers:
    - ericmjl
    - canyon289
    - aloctavodia
    - ColCarroll
    - ahartikainen
