{% set name = "arviz" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0a796cccda61dbd26aad36d0258bb46bb3c412e41176d3b9fbbb49c2a69be12
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - matplotlib >=3.0
    - numpy
    - scipy
    - pandas
    - xarray
    - netcdf4

test:
  imports:
    - arviz

about:
  home: https://github.com/arviz-devs/arviz
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Exploratory analysis of Bayesian models with Python'

  description: |
    ArviZ (pronounced "AR-vees") is a Python package for exploratory analysis
    of Bayesian models. Includes functions for posterior analysis, model
    checking, comparison and diagnostics.

  doc_url: https://arviz-devs.github.io/arviz/index.html
  dev_url: https://github.com/arviz-devs/arviz

extra:
  recipe-maintainers:
    - ericmjl
    - canyon289
    - aloctavodia
    - ColCarroll
    - ahartikainen
