{% set name = "arviz" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7172c60980d47a93c3ff29be554fbeba33287e8aea88082956386b82cf995f1b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<312]

requirements:
  host:
    - python
    - pip
    - flit-core >=3.4,<4
  run:
    - python
    - arviz-base >=1.1.0,<1.2.0
    - arviz-stats >=1.1.0,<1.2.0
    # arviz-stats[xarray]>=1.1,<1.2: xarray-einstats", "xarray>=2024.11.0"
    # see https://github.com/arviz-devs/arviz-stats/blob/v1.1.0/pyproject.toml#L43-L47
    - xarray-einstats >=0.9.1,<0.10.0
    - xarray >=2024.11.0
    - arviz-plots >=1.1.0,<1.2.0
    - matplotlib-base >=3.9

test:
  imports:
    - arviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://python.arviz.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Exploratory analysis of Bayesian models with Python
  description: |
    ArviZ (pronounced "AR-vees") is a Python package for exploratory analysis
    of Bayesian models. Includes functions for posterior analysis, model
    checking, comparison and diagnostics.
  doc_url: https://python.arviz.org
  dev_url: https://github.com/arviz-devs/arviz

extra:
  recipe-maintainers:
    - ericmjl
    - canyon289
    - aloctavodia
    - ColCarroll
    - ahartikainen
