travis:
  secure:
    BINSTAR_TOKEN: bhZyqZYCH9zhR8iNeo7NSLK0WSg0mpwNa2eAKJQvHao0NNNVAWLo2CKsGUPXNlydWuOT+jEWwFSb5CeY2B62+7hWaBpmFpuTmK5Ee1zG0aqlxVHXL2YPcRxnW4N2Gdh7wXYjSogTV0kdI2eIOZoGmWovS2b25OZLNIsgpI/rsuE3utNoBPw7wlS23oBm5ENdel5k0YP5qHVUUIowq+6XgDW+1PqptFbaV1lMY/jNnJT2T6EqamJMtREC6/RaUOYgAl2QmIweLlPc25kgIqzOljwk96AHKnXntpnnSHG4iJGa2kJG+Wz7SHPAPq+sW0qFZ4Y56GhzOXswfnZhWDdfG6pRKdgMOtt5zOBzkeWXIvT5fBJY3t3jwwvIKNNqKntd5g5lh9rvWv9tonS0aDhirvI10szAL5nHVLAvVg1w1uIp11ExRiJdj1Gs72e2voIPsL8ng6QS2KQMHw51OVr6U81Xs7erjvM/OhR4QBHjV2jxA/ilpM5zXtjA82NdQQO8XduQVBTJbKSCGVdyQ5MLvDGfvnUw3I1IXD3J5nFhPygxORJgDooN4ymBAundT7DI1hAaoxNkkP2Zf2LYLdA6bIotx4W/aJL7p2e8uhQvYpTFYGPbiqZmrdddt6yZpkLsJZ1Few2WNtCQ7FvWTQsKaEgBXrRlwoGo6EQy4blzyfs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
